env:
  TZ: UTC
  STATICCHECK_VERSION: "v0.7.0"
  DIFFER_VERSION: "v0.0.0-20260403230520-c0574ebcacb2"

steps:
  - label: ":go: Format"
    key: "format"
    command: ".buildkite/ci/format.sh"
    timeout_in_minutes: 10
    agents:
      vm: "buildkite"
      host: "caracal"
    artifact_paths:
      - "reports/format/**/*"

  - label: ":go: Lint"
    key: "lint"
    command: ".buildkite/ci/lint.sh"
    timeout_in_minutes: 10
    agents:
      vm: "buildkite"
      host: "caracal"
    artifact_paths:
      - "reports/lint/**/*"

  - label: ":go: Test"
    key: "test"
    command: ".buildkite/ci/test.sh"
    timeout_in_minutes: 15
    agents:
      vm: "buildkite"
      host: "caracal"
    artifact_paths:
      - "reports/tests/**/*"
      - "coverage/**/*"

  - label: ":go: Build"
    key: "build"
    command: ".buildkite/ci/build.sh"
    timeout_in_minutes: 10
    depends_on:
      - "format"
      - "lint"
      - "test"
    agents:
      vm: "buildkite"
      host: "caracal"
    artifact_paths:
      - "dist/**/*"
      - "reports/build/**/*"
