env:
  TZ: UTC
  GO111MODULE: "on"
  GO_VERSION: "1.25.3"

steps:
  - label: ":golang: Test"
    commands:
      - "source .buildkite/setup-go.sh"
      - "go fmt ./..."
      - "go vet ./..."
      - "go run honnef.co/go/tools/cmd/staticcheck@latest ./..."
      - "go test -trimpath -race -cover ./..."
      - "go build -trimpath ./..."
