package lib

import (
	"encoding/json"
	"testing"
)

var buildsResponse = []byte(`
[
    {
        "id": "071e0979-8671-4904-be5a-0b18fb5ba09b",
        "graphql_id": "QnVpbGQtLS0wNzFlMDk3OS04NjcxLTQ5MDQtYmU1YS0wYjE4ZmI1YmEwOWI=",
        "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944",
        "web_url": "https://buildkite.com/example/example_repo/builds/944",
        "number": 944,
        "state": "running",
        "blocked": false,
        "blocked_state": "",
        "message": "span/kafka: skip tests with offline Kafka server\n\nThese tests cause CI failures when we ask the CI environment to run\nthe spancat tests.\n\nFixes #166.",
        "commit": "4416ce9a1bbd38505c72f8f9d034a45c41b02a02",
        "branch": "master",
        "tag": null,
        "env": {},
        "source": "webhook",
        "author": {
            "username": "kevinburkeexample",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com"
        },
        "creator": {
            "id": "96ba0039-c9f3-45bb-8039-23705197a20d",
            "graphql_id": "VXNlci0tLTk2YmEwMDM5LWM5ZjMtNDViYi04MDM5LTIzNzA1MTk3YTIwZA==",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com",
            "avatar_url": "https://www.gravatar.com/avatar/b6fb7afdae89b8470c0bed5b5ea7156c",
            "created_at": "2021-12-15T22:37:55.752Z"
        },
        "created_at": "2022-03-08T19:15:54.616Z",
        "scheduled_at": "2022-03-08T19:15:54.593Z",
        "started_at": "2022-03-08T19:15:59.447Z",
        "finished_at": null,
        "meta_data": {
            "buildkite:git:commit": "commit 4416ce9a1bbd38505c72f8f9d034a45c41b02a02\nAuthor:     Kevin Burke <kevin.burke@example.com>\nAuthorDate: Mon Mar 7 21:46:05 2022 -0800\nCommit:     Kevin Burke <kevin.burke@example.com>\nCommitDate: Tue Mar 8 10:15:32 2022 -0800\n\n    span/kafka: skip tests with offline Kafka server\n    \n    These tests cause CI failures when we ask the CI environment to run\n    the spancat tests.\n    \n    Fixes #166."
        },
        "pull_request": null,
        "rebuilt_from": null,
        "pipeline": {
            "id": "632fa93f-af7b-4bbb-a2be-58f1f6f18300",
            "graphql_id": "UGlwZWxpbmUtLS02MzJmYTkzZi1hZjdiLTRiYmItYTJiZS01OGYxZjZmMTgzMDA=",
            "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo",
            "web_url": "https://buildkite.com/example/example_repo",
            "name": "example_repo",
            "description": null,
            "slug": "example_repo",
            "repository": "git@github.com:example/example_repo.git",
            "cluster_id": null,
            "branch_configuration": null,
            "default_branch": "master",
            "skip_queued_branch_builds": false,
            "skip_queued_branch_builds_filter": null,
            "cancel_running_branch_builds": false,
            "cancel_running_branch_builds_filter": null,
            "allow_rebuilds": true,
            "provider": {
                "id": "github",
                "settings": {
                    "trigger_mode": "code",
                    "build_pull_requests": true,
                    "pull_request_branch_filter_enabled": false,
                    "skip_builds_for_existing_commits": false,
                    "skip_pull_request_builds_for_existing_commits": true,
                    "build_pull_request_ready_for_review": false,
                    "build_pull_request_labels_changed": false,
                    "build_pull_request_forks": false,
                    "prefix_pull_request_fork_branch_names": true,
                    "build_branches": true,
                    "build_tags": false,
                    "cancel_deleted_branch_builds": false,
                    "publish_commit_status": true,
                    "publish_commit_status_per_step": false,
                    "separate_pull_request_statuses": false,
                    "publish_blocked_as_pending": false,
                    "use_step_key_as_commit_status": false,
                    "filter_enabled": false,
                    "repository": "example/example_repo"
                },
                "webhook_url": "https://webhook.buildkite.com/deliver/a8b7d1ec0e383c14108b9d814c76173fe17da74ae1f35a5f0c"
            },
            "builds_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds",
            "badge_url": "https://badge.buildkite.com/7d154fae54d51f386ce4db0a5f1194690e614425ea9f3726ba.svg",
            "created_by": {
                "id": "52ddcfda-658d-404a-b2d2-b006f3c7a2ad",
                "graphql_id": "VXNlci0tLTUyZGRjZmRhLTY1OGQtNDA0YS1iMmQyLWIwMDZmM2M3YTJhZA==",
                "name": "Buildkite Bot",
                "email": "tooling-team+buildkite-bot@example.com",
                "avatar_url": "https://www.gravatar.com/avatar/f802d3f82304aaebaed6d934e9ce231c",
                "created_at": "2019-06-26T00:02:51.775Z"
            },
            "created_at": "2020-07-28T23:16:52.812Z",
            "archived_at": null,
            "env": {},
            "scheduled_builds_count": 0,
            "running_builds_count": 1,
            "scheduled_jobs_count": 0,
            "running_jobs_count": 2,
            "waiting_jobs_count": 0,
            "visibility": "private",
            "tags": null,
            "steps": [
                {
                    "type": "script",
                    "name": ":pipeline:",
                    "command": "buildkite-agent pipeline upload",
                    "artifact_paths": null,
                    "branch_configuration": null,
                    "env": {},
                    "timeout_in_minutes": null,
                    "agent_query_rules": [],
                    "concurrency": null,
                    "parallelism": null
                }
            ]
        },
        "jobs": [
            {
                "id": "fca912da-fe38-4bf5-b8df-980ce0367aff",
                "graphql_id": "Sm9iLS0tZmNhOTEyZGEtZmUzOC00YmY1LWI4ZGYtOTgwY2UwMzY3YWZm",
                "type": "script",
                "name": ":pipeline:",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944",
                "web_url": "https://buildkite.com/example/example_repo/builds/944#fca912da-fe38-4bf5-b8df-980ce0367aff",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/fca912da-fe38-4bf5-b8df-980ce0367aff/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/fca912da-fe38-4bf5-b8df-980ce0367aff/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/fca912da-fe38-4bf5-b8df-980ce0367aff/artifacts",
                "command": "buildkite-agent pipeline upload",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "ea21056f-2e4f-45e2-af25-6a184c30cc3e",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/ea21056f-2e4f-45e2-af25-6a184c30cc3e",
                    "web_url": "https://buildkite.com/organizations/example/agents/ea21056f-2e4f-45e2-af25-6a184c30cc3e",
                    "name": "buildkite-ci-033404905f9532bfd",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-033404905f9532bfd",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T18:46:08.520Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:16:14.460Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=green-prod",
                        "aws:instance-id=i-033404905f9532bfd",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "Name=buildkite-v1-green-0",
                        "aws:ec2launchtemplate:id=lt-00d7f6fc105994097",
                        "kind=buildkite",
                        "queues=v1,default,green-prod",
                        "aws:autoscaling:groupName=buildkite-v1-green-0",
                        "aws:ec2:fleet-id=fleet-f6cba4e3-57d7-ea11-a41a-830226b1deab",
                        "aws:ec2launchtemplate:version=4",
                        "debug=false",
                        "name=buildkite-v1-green-0"
                    ]
                },
                "created_at": "2022-03-08T19:15:54.607Z",
                "scheduled_at": "2022-03-08T19:15:54.607Z",
                "runnable_at": "2022-03-08T19:15:54.703Z",
                "started_at": "2022-03-08T19:15:59.447Z",
                "finished_at": "2022-03-08T19:16:14.429Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "a91ee8ba-b32e-4534-ac5b-221e28cbacb0",
                "graphql_id": "Sm9iLS0tYTkxZWU4YmEtYjMyZS00NTM0LWFjNWItMjIxZTI4Y2JhY2Iw",
                "type": "script",
                "name": "test",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "running",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944",
                "web_url": "https://buildkite.com/example/example_repo/builds/944#a91ee8ba-b32e-4534-ac5b-221e28cbacb0",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/a91ee8ba-b32e-4534-ac5b-221e28cbacb0/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/a91ee8ba-b32e-4534-ac5b-221e28cbacb0/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/a91ee8ba-b32e-4534-ac5b-221e28cbacb0/artifacts",
                "command": "make deps\nmake vendor\nbk-snyk\nmake test\n",
                "soft_failed": false,
                "exit_status": null,
                "artifact_paths": null,
                "agent": {
                    "id": "81745862-79f9-4586-acbc-9294775413ef",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/81745862-79f9-4586-acbc-9294775413ef",
                    "web_url": "https://buildkite.com/organizations/example/agents/81745862-79f9-4586-acbc-9294775413ef",
                    "name": "buildkite-ci-08ad47255e6b75f7d",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-08ad47255e6b75f7d",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T18:26:42.217Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:03:00.576Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-08ad47255e6b75f7d",
                        "debug=false",
                        "Name=buildkite-v1-0",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "name=buildkite-v1-0",
                        "queues=v1,default,blue-prod",
                        "aws:ec2:fleet-id=fleet-7ceb0cc3-5dfd-e011-8eb8-0b02875bf4ea",
                        "aws:ec2launchtemplate:version=11",
                        "kind=buildkite"
                    ]
                },
                "created_at": "2022-03-08T19:16:10.402Z",
                "scheduled_at": "2022-03-08T19:15:54.607Z",
                "runnable_at": "2022-03-08T19:16:10.463Z",
                "started_at": "2022-03-08T19:16:13.509Z",
                "finished_at": null,
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "1d463a6c-dfde-4d0f-9450-9aac99a9ae70",
                "graphql_id": "Sm9iLS0tMWQ0NjNhNmMtZGZkZS00ZDBmLTk0NTAtOWFhYzk5YTlhZTcw",
                "type": "script",
                "name": "publish",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "assigned",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944",
                "web_url": "https://buildkite.com/example/example_repo/builds/944#1d463a6c-dfde-4d0f-9450-9aac99a9ae70",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/1d463a6c-dfde-4d0f-9450-9aac99a9ae70/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/1d463a6c-dfde-4d0f-9450-9aac99a9ae70/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/944/jobs/1d463a6c-dfde-4d0f-9450-9aac99a9ae70/artifacts",
                "command": "make vendor\nmake publish branch=master commit=4416ce9\nmake publish branch=master commit=4416ce9 tags=debug\nbuildkite-agent annotate \"Image: $(make image branch=master commit=4416ce9)\" --style 'success' --context 'ctx-success'\nbuildkite-agent annotate \"Debug image: $(make image branch=master commit=4416ce9 tags=debug)\" --style 'info' --context 'ctx-success'\n",
                "soft_failed": false,
                "exit_status": null,
                "artifact_paths": null,
                "agent": {
                    "id": "c88c7046-b4e0-44bf-9f76-7c8a9d5d5b69",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/c88c7046-b4e0-44bf-9f76-7c8a9d5d5b69",
                    "web_url": "https://buildkite.com/organizations/example/agents/c88c7046-b4e0-44bf-9f76-7c8a9d5d5b69",
                    "name": "buildkite-ci-0fd5d67ba2baafdc2",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-0fd5d67ba2baafdc2",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T18:36:57.710Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:02:27.854Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-0fd5d67ba2baafdc2",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "debug=false",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "aws:ec2:fleet-id=fleet-544b0669-755f-48b3-26b2-01a2c868555d",
                        "kind=buildkite",
                        "name=buildkite-v1-0",
                        "queues=v1,default,blue-prod",
                        "Name=buildkite-v1-0",
                        "aws:ec2launchtemplate:version=11"
                    ]
                },
                "created_at": "2022-03-08T19:16:10.402Z",
                "scheduled_at": "2022-03-08T19:15:54.607Z",
                "runnable_at": "2022-03-08T19:16:10.463Z",
                "started_at": null,
                "finished_at": null,
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            }
        ]
    },
    {
        "id": "53e3f666-28f0-4f08-8de0-c0f6c38fe037",
        "graphql_id": "QnVpbGQtLS01M2UzZjY2Ni0yOGYwLTRmMDgtOGRlMC1jMGY2YzM4ZmUwMzc=",
        "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943",
        "web_url": "https://buildkite.com/example/example_repo/builds/943",
        "number": 943,
        "state": "passed",
        "blocked": false,
        "blocked_state": "",
        "message": "span/kafka: skip tests with offline Kafka server\n\nThese tests cause CI failures when we ask the CI environment to run\nthe spancat tests.\n\nFixes #166.",
        "commit": "4416ce9a1bbd38505c72f8f9d034a45c41b02a02",
        "branch": "spancat-ci",
        "tag": null,
        "env": {},
        "source": "webhook",
        "author": {
            "username": "kevinburkeexample",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com"
        },
        "creator": {
            "id": "96ba0039-c9f3-45bb-8039-23705197a20d",
            "graphql_id": "VXNlci0tLTk2YmEwMDM5LWM5ZjMtNDViYi04MDM5LTIzNzA1MTk3YTIwZA==",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com",
            "avatar_url": "https://www.gravatar.com/avatar/b6fb7afdae89b8470c0bed5b5ea7156c",
            "created_at": "2021-12-15T22:37:55.752Z"
        },
        "created_at": "2022-03-08T18:15:36.301Z",
        "scheduled_at": "2022-03-08T18:15:36.268Z",
        "started_at": "2022-03-08T18:15:37.813Z",
        "finished_at": "2022-03-08T18:17:36.199Z",
        "meta_data": {
            "buildkite:git:commit": "commit 4416ce9a1bbd38505c72f8f9d034a45c41b02a02\nAuthor:     Kevin Burke <kevin.burke@example.com>\nAuthorDate: Mon Mar 7 21:46:05 2022 -0800\nCommit:     Kevin Burke <kevin.burke@example.com>\nCommitDate: Tue Mar 8 10:15:32 2022 -0800\n\n    span/kafka: skip tests with offline Kafka server\n    \n    These tests cause CI failures when we ask the CI environment to run\n    the spancat tests.\n    \n    Fixes #166."
        },
        "pull_request": {
            "id": "167",
            "base": "master",
            "repository": "git://github.com/example/example_repo.git"
        },
        "rebuilt_from": null,
        "pipeline": {
            "id": "632fa93f-af7b-4bbb-a2be-58f1f6f18300",
            "graphql_id": "UGlwZWxpbmUtLS02MzJmYTkzZi1hZjdiLTRiYmItYTJiZS01OGYxZjZmMTgzMDA=",
            "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo",
            "web_url": "https://buildkite.com/example/example_repo",
            "name": "example_repo",
            "description": null,
            "slug": "example_repo",
            "repository": "git@github.com:example/example_repo.git",
            "cluster_id": null,
            "branch_configuration": null,
            "default_branch": "master",
            "skip_queued_branch_builds": false,
            "skip_queued_branch_builds_filter": null,
            "cancel_running_branch_builds": false,
            "cancel_running_branch_builds_filter": null,
            "allow_rebuilds": true,
            "provider": {
                "id": "github",
                "settings": {
                    "trigger_mode": "code",
                    "build_pull_requests": true,
                    "pull_request_branch_filter_enabled": false,
                    "skip_builds_for_existing_commits": false,
                    "skip_pull_request_builds_for_existing_commits": true,
                    "build_pull_request_ready_for_review": false,
                    "build_pull_request_labels_changed": false,
                    "build_pull_request_forks": false,
                    "prefix_pull_request_fork_branch_names": true,
                    "build_branches": true,
                    "build_tags": false,
                    "cancel_deleted_branch_builds": false,
                    "publish_commit_status": true,
                    "publish_commit_status_per_step": false,
                    "separate_pull_request_statuses": false,
                    "publish_blocked_as_pending": false,
                    "use_step_key_as_commit_status": false,
                    "filter_enabled": false,
                    "repository": "example/example_repo"
                },
                "webhook_url": "https://webhook.buildkite.com/deliver/a8b7d1ec0e383c14108b9d814c76173fe17da74ae1f35a5f0c"
            },
            "builds_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds",
            "badge_url": "https://badge.buildkite.com/7d154fae54d51f386ce4db0a5f1194690e614425ea9f3726ba.svg",
            "created_by": {
                "id": "52ddcfda-658d-404a-b2d2-b006f3c7a2ad",
                "graphql_id": "VXNlci0tLTUyZGRjZmRhLTY1OGQtNDA0YS1iMmQyLWIwMDZmM2M3YTJhZA==",
                "name": "Buildkite Bot",
                "email": "tooling-team+buildkite-bot@example.com",
                "avatar_url": "https://www.gravatar.com/avatar/f802d3f82304aaebaed6d934e9ce231c",
                "created_at": "2019-06-26T00:02:51.775Z"
            },
            "created_at": "2020-07-28T23:16:52.812Z",
            "archived_at": null,
            "env": {},
            "scheduled_builds_count": 0,
            "running_builds_count": 1,
            "scheduled_jobs_count": 0,
            "running_jobs_count": 2,
            "waiting_jobs_count": 0,
            "visibility": "private",
            "tags": null,
            "steps": [
                {
                    "type": "script",
                    "name": ":pipeline:",
                    "command": "buildkite-agent pipeline upload",
                    "artifact_paths": null,
                    "branch_configuration": null,
                    "env": {},
                    "timeout_in_minutes": null,
                    "agent_query_rules": [],
                    "concurrency": null,
                    "parallelism": null
                }
            ]
        },
        "jobs": [
            {
                "id": "5ee91b85-8f51-4f04-a2ca-64814c631afa",
                "graphql_id": "Sm9iLS0tNWVlOTFiODUtOGY1MS00ZjA0LWEyY2EtNjQ4MTRjNjMxYWZh",
                "type": "script",
                "name": ":pipeline:",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943",
                "web_url": "https://buildkite.com/example/example_repo/builds/943#5ee91b85-8f51-4f04-a2ca-64814c631afa",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/5ee91b85-8f51-4f04-a2ca-64814c631afa/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/5ee91b85-8f51-4f04-a2ca-64814c631afa/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/5ee91b85-8f51-4f04-a2ca-64814c631afa/artifacts",
                "command": "buildkite-agent pipeline upload",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "51a78a5a-07cc-4784-ad71-4c09e4a0b394",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/51a78a5a-07cc-4784-ad71-4c09e4a0b394",
                    "web_url": "https://buildkite.com/organizations/example/agents/51a78a5a-07cc-4784-ad71-4c09e4a0b394",
                    "name": "buildkite-ci-0f229bba14012b3db",
                    "connection_state": "disconnected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-0f229bba14012b3db",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T18:00:46.896Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T18:51:27.642Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-0f229bba14012b3db",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "aws:ec2launchtemplate:version=11",
                        "debug=false",
                        "queues=v1,default,blue-prod",
                        "Name=buildkite-v1-0",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "aws:ec2:fleet-id=fleet-d6612e49-5dd7-6833-84b8-8900c9c0b26a",
                        "kind=buildkite",
                        "name=buildkite-v1-0"
                    ]
                },
                "created_at": "2022-03-08T18:15:36.289Z",
                "scheduled_at": "2022-03-08T18:15:36.289Z",
                "runnable_at": "2022-03-08T18:15:36.371Z",
                "started_at": "2022-03-08T18:15:37.813Z",
                "finished_at": "2022-03-08T18:15:51.658Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "a3774abc-0b4f-4167-aa8f-aab981ce37a8",
                "graphql_id": "Sm9iLS0tYTM3NzRhYmMtMGI0Zi00MTY3LWFhOGYtYWFiOTgxY2UzN2E4",
                "type": "script",
                "name": "test",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943",
                "web_url": "https://buildkite.com/example/example_repo/builds/943#a3774abc-0b4f-4167-aa8f-aab981ce37a8",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/a3774abc-0b4f-4167-aa8f-aab981ce37a8/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/a3774abc-0b4f-4167-aa8f-aab981ce37a8/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/a3774abc-0b4f-4167-aa8f-aab981ce37a8/artifacts",
                "command": "make deps\nmake vendor\nbk-snyk\nmake test\n",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "4a7b26d8-ded9-40de-86a4-8d42ab6289c6",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/4a7b26d8-ded9-40de-86a4-8d42ab6289c6",
                    "web_url": "https://buildkite.com/organizations/example/agents/4a7b26d8-ded9-40de-86a4-8d42ab6289c6",
                    "name": "buildkite-ci-058fbac1e17c0d0d9",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-058fbac1e17c0d0d9",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T15:48:16.295Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:02:19.161Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-058fbac1e17c0d0d9",
                        "aws:ec2:fleet-id=fleet-decb2ce3-d5d7-c0bb-861a-0188140c9b03",
                        "aws:ec2launchtemplate:version=11",
                        "kind=buildkite",
                        "name=buildkite-v1-0",
                        "queues=v1,default,blue-prod",
                        "Name=buildkite-v1-0",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "debug=false"
                    ]
                },
                "created_at": "2022-03-08T18:15:47.821Z",
                "scheduled_at": "2022-03-08T18:15:36.289Z",
                "runnable_at": "2022-03-08T18:15:47.983Z",
                "started_at": "2022-03-08T18:15:57.313Z",
                "finished_at": "2022-03-08T18:17:32.238Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "24cf1765-f17b-476a-ad62-2fed208dbfe3",
                "graphql_id": "Sm9iLS0tMjRjZjE3NjUtZjE3Yi00NzZhLWFkNjItMmZlZDIwOGRiZmUz",
                "type": "script",
                "name": "publish",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943",
                "web_url": "https://buildkite.com/example/example_repo/builds/943#24cf1765-f17b-476a-ad62-2fed208dbfe3",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/24cf1765-f17b-476a-ad62-2fed208dbfe3/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/24cf1765-f17b-476a-ad62-2fed208dbfe3/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/943/jobs/24cf1765-f17b-476a-ad62-2fed208dbfe3/artifacts",
                "command": "make vendor\nmake publish branch=spancat-ci commit=4416ce9\nmake publish branch=spancat-ci commit=4416ce9 tags=debug\nbuildkite-agent annotate \"Image: $(make image branch=spancat-ci commit=4416ce9)\" --style 'success' --context 'ctx-success'\nbuildkite-agent annotate \"Debug image: $(make image branch=spancat-ci commit=4416ce9 tags=debug)\" --style 'info' --context 'ctx-success'\n",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "1040444a-9a68-4cac-9bf2-68a18bec105c",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/1040444a-9a68-4cac-9bf2-68a18bec105c",
                    "web_url": "https://buildkite.com/organizations/example/agents/1040444a-9a68-4cac-9bf2-68a18bec105c",
                    "name": "buildkite-ci-023a6c122a0335a5f",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-023a6c122a0335a5f",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T17:23:15.037Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:03:56.303Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-023a6c122a0335a5f",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "Name=buildkite-v1-0",
                        "aws:ec2:fleet-id=fleet-dcc92463-75df-409b-8eb0-29a28c2618c8",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "aws:ec2launchtemplate:version=11",
                        "debug=false",
                        "kind=buildkite",
                        "name=buildkite-v1-0",
                        "queues=v1,default,blue-prod"
                    ]
                },
                "created_at": "2022-03-08T18:15:47.821Z",
                "scheduled_at": "2022-03-08T18:15:36.289Z",
                "runnable_at": "2022-03-08T18:15:47.983Z",
                "started_at": "2022-03-08T18:15:56.179Z",
                "finished_at": "2022-03-08T18:17:35.967Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            }
        ]
    },
    {
        "id": "8cdf262f-eee4-4131-a42a-c5f717dedd38",
        "graphql_id": "QnVpbGQtLS04Y2RmMjYyZi1lZWU0LTQxMzEtYTQyYS1jNWY3MTdkZWRkMzg=",
        "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942",
        "web_url": "https://buildkite.com/example/example_repo/builds/942",
        "number": 942,
        "state": "passed",
        "blocked": false,
        "blocked_state": "",
        "message": "tracedb: fix spelling mistakes",
        "commit": "4191d6c81c7ad9e247a238a23c4d3f233d83472e",
        "branch": "master",
        "tag": null,
        "env": {},
        "source": "webhook",
        "author": {
            "username": "kevinburkeexample",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com"
        },
        "creator": {
            "id": "96ba0039-c9f3-45bb-8039-23705197a20d",
            "graphql_id": "VXNlci0tLTk2YmEwMDM5LWM5ZjMtNDViYi04MDM5LTIzNzA1MTk3YTIwZA==",
            "name": "Kevin Burke",
            "email": "kevin.burke@example.com",
            "avatar_url": "https://www.gravatar.com/avatar/b6fb7afdae89b8470c0bed5b5ea7156c",
            "created_at": "2021-12-15T22:37:55.752Z"
        },
        "created_at": "2022-03-08T18:15:25.291Z",
        "scheduled_at": "2022-03-08T18:15:25.236Z",
        "started_at": "2022-03-08T18:15:28.352Z",
        "finished_at": "2022-03-08T18:17:21.157Z",
        "meta_data": {
            "buildkite:git:commit": "commit 4191d6c81c7ad9e247a238a23c4d3f233d83472e\nAuthor:     Kevin Burke <kevin.burke@example.com>\nAuthorDate: Wed Feb 23 16:37:24 2022 -0800\nCommit:     Kevin Burke <kevin.burke@example.com>\nCommitDate: Tue Mar 8 10:10:07 2022 -0800\n\n    tracedb: fix spelling mistakes"
        },
        "pull_request": null,
        "rebuilt_from": null,
        "pipeline": {
            "id": "632fa93f-af7b-4bbb-a2be-58f1f6f18300",
            "graphql_id": "UGlwZWxpbmUtLS02MzJmYTkzZi1hZjdiLTRiYmItYTJiZS01OGYxZjZmMTgzMDA=",
            "url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo",
            "web_url": "https://buildkite.com/example/example_repo",
            "name": "example_repo",
            "description": null,
            "slug": "example_repo",
            "repository": "git@github.com:example/example_repo.git",
            "cluster_id": null,
            "branch_configuration": null,
            "default_branch": "master",
            "skip_queued_branch_builds": false,
            "skip_queued_branch_builds_filter": null,
            "cancel_running_branch_builds": false,
            "cancel_running_branch_builds_filter": null,
            "allow_rebuilds": true,
            "provider": {
                "id": "github",
                "settings": {
                    "trigger_mode": "code",
                    "build_pull_requests": true,
                    "pull_request_branch_filter_enabled": false,
                    "skip_builds_for_existing_commits": false,
                    "skip_pull_request_builds_for_existing_commits": true,
                    "build_pull_request_ready_for_review": false,
                    "build_pull_request_labels_changed": false,
                    "build_pull_request_forks": false,
                    "prefix_pull_request_fork_branch_names": true,
                    "build_branches": true,
                    "build_tags": false,
                    "cancel_deleted_branch_builds": false,
                    "publish_commit_status": true,
                    "publish_commit_status_per_step": false,
                    "separate_pull_request_statuses": false,
                    "publish_blocked_as_pending": false,
                    "use_step_key_as_commit_status": false,
                    "filter_enabled": false,
                    "repository": "example/example_repo"
                },
                "webhook_url": "https://webhook.buildkite.com/deliver/a8b7d1ec0e383c14108b9d814c76173fe17da74ae1f35a5f0c"
            },
            "builds_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds",
            "badge_url": "https://badge.buildkite.com/7d154fae54d51f386ce4db0a5f1194690e614425ea9f3726ba.svg",
            "created_by": {
                "id": "52ddcfda-658d-404a-b2d2-b006f3c7a2ad",
                "graphql_id": "VXNlci0tLTUyZGRjZmRhLTY1OGQtNDA0YS1iMmQyLWIwMDZmM2M3YTJhZA==",
                "name": "Buildkite Bot",
                "email": "tooling-team+buildkite-bot@example.com",
                "avatar_url": "https://www.gravatar.com/avatar/f802d3f82304aaebaed6d934e9ce231c",
                "created_at": "2019-06-26T00:02:51.775Z"
            },
            "created_at": "2020-07-28T23:16:52.812Z",
            "archived_at": null,
            "env": {},
            "scheduled_builds_count": 0,
            "running_builds_count": 1,
            "scheduled_jobs_count": 0,
            "running_jobs_count": 2,
            "waiting_jobs_count": 0,
            "visibility": "private",
            "tags": null,
            "steps": [
                {
                    "type": "script",
                    "name": ":pipeline:",
                    "command": "buildkite-agent pipeline upload",
                    "artifact_paths": null,
                    "branch_configuration": null,
                    "env": {},
                    "timeout_in_minutes": null,
                    "agent_query_rules": [],
                    "concurrency": null,
                    "parallelism": null
                }
            ]
        },
        "jobs": [
            {
                "id": "b95ea516-9928-4cd5-9c9d-cb6858d69085",
                "graphql_id": "Sm9iLS0tYjk1ZWE1MTYtOTkyOC00Y2Q1LTljOWQtY2I2ODU4ZDY5MDg1",
                "type": "script",
                "name": ":pipeline:",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942",
                "web_url": "https://buildkite.com/example/example_repo/builds/942#b95ea516-9928-4cd5-9c9d-cb6858d69085",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/b95ea516-9928-4cd5-9c9d-cb6858d69085/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/b95ea516-9928-4cd5-9c9d-cb6858d69085/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/b95ea516-9928-4cd5-9c9d-cb6858d69085/artifacts",
                "command": "buildkite-agent pipeline upload",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "7fe65946-ecfc-4426-9469-e3d5b0e55b4b",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/7fe65946-ecfc-4426-9469-e3d5b0e55b4b",
                    "web_url": "https://buildkite.com/organizations/example/agents/7fe65946-ecfc-4426-9469-e3d5b0e55b4b",
                    "name": "buildkite-ci-095c35ea8780c437b",
                    "connection_state": "disconnected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-095c35ea8780c437b",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T16:20:07.106Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T18:38:19.834Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-id=i-095c35ea8780c437b",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "name=buildkite-v1-0",
                        "queues=v1,default,blue-prod",
                        "aws:ec2:fleet-id=fleet-54c30441-dd5d-6039-863a-a1a861071894",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "aws:ec2launchtemplate:version=11",
                        "kind=buildkite",
                        "Name=buildkite-v1-0",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "debug=false"
                    ]
                },
                "created_at": "2022-03-08T18:15:25.264Z",
                "scheduled_at": "2022-03-08T18:15:25.264Z",
                "runnable_at": "2022-03-08T18:15:25.349Z",
                "started_at": "2022-03-08T18:15:28.352Z",
                "finished_at": "2022-03-08T18:15:41.417Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "1a05f51d-8449-4e80-a1b5-a264639ee830",
                "graphql_id": "Sm9iLS0tMWEwNWY1MWQtODQ0OS00ZTgwLWExYjUtYTI2NDYzOWVlODMw",
                "type": "script",
                "name": "test",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942",
                "web_url": "https://buildkite.com/example/example_repo/builds/942#1a05f51d-8449-4e80-a1b5-a264639ee830",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/1a05f51d-8449-4e80-a1b5-a264639ee830/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/1a05f51d-8449-4e80-a1b5-a264639ee830/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/1a05f51d-8449-4e80-a1b5-a264639ee830/artifacts",
                "command": "make deps\nmake vendor\nbk-snyk\nmake test\n",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "769417cd-b250-4768-bc40-88a9b1cfc680",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/769417cd-b250-4768-bc40-88a9b1cfc680",
                    "web_url": "https://buildkite.com/organizations/example/agents/769417cd-b250-4768-bc40-88a9b1cfc680",
                    "name": "buildkite-ci-00d5adc72422aaa72",
                    "connection_state": "lost",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-00d5adc72422aaa72",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T15:43:34.285Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T18:23:02.534Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=green-prod",
                        "aws:instance-id=i-00d5adc72422aaa72",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:ec2launchtemplate:version=4",
                        "debug=false",
                        "queues=v1,default,green-prod",
                        "Name=buildkite-v1-green-0",
                        "aws:autoscaling:groupName=buildkite-v1-green-0",
                        "aws:ec2:fleet-id=fleet-5ec3a6cb-5ff5-4a19-0692-290086fc65c7",
                        "aws:ec2launchtemplate:id=lt-00d7f6fc105994097",
                        "kind=buildkite",
                        "name=buildkite-v1-green-0"
                    ]
                },
                "created_at": "2022-03-08T18:15:37.539Z",
                "scheduled_at": "2022-03-08T18:15:25.264Z",
                "runnable_at": "2022-03-08T18:15:37.620Z",
                "started_at": "2022-03-08T18:15:45.126Z",
                "finished_at": "2022-03-08T18:17:06.802Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            },
            {
                "id": "dce09438-fe14-4591-9a1a-3d8598805a73",
                "graphql_id": "Sm9iLS0tZGNlMDk0MzgtZmUxNC00NTkxLTlhMWEtM2Q4NTk4ODA1YTcz",
                "type": "script",
                "name": "publish",
                "step_key": null,
                "priority": {
                    "number": 0
                },
                "agent_query_rules": [
                    "queue=v1"
                ],
                "state": "passed",
                "build_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942",
                "web_url": "https://buildkite.com/example/example_repo/builds/942#dce09438-fe14-4591-9a1a-3d8598805a73",
                "log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/dce09438-fe14-4591-9a1a-3d8598805a73/log",
                "raw_log_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/dce09438-fe14-4591-9a1a-3d8598805a73/log.txt",
                "artifacts_url": "https://api.buildkite.com/v2/organizations/example/pipelines/example_repo/builds/942/jobs/dce09438-fe14-4591-9a1a-3d8598805a73/artifacts",
                "command": "make vendor\nmake publish branch=master commit=4191d6c\nmake publish branch=master commit=4191d6c tags=debug\nbuildkite-agent annotate \"Image: $(make image branch=master commit=4191d6c)\" --style 'success' --context 'ctx-success'\nbuildkite-agent annotate \"Debug image: $(make image branch=master commit=4191d6c tags=debug)\" --style 'info' --context 'ctx-success'\n",
                "soft_failed": false,
                "exit_status": 0,
                "artifact_paths": null,
                "agent": {
                    "id": "4bfc8aea-94f4-4ef4-a5cd-6ac3b713dc93",
                    "url": "https://api.buildkite.com/v2/organizations/example/agents/4bfc8aea-94f4-4ef4-a5cd-6ac3b713dc93",
                    "web_url": "https://buildkite.com/organizations/example/agents/4bfc8aea-94f4-4ef4-a5cd-6ac3b713dc93",
                    "name": "buildkite-ci-0c2ce33582ef1613d",
                    "connection_state": "connected",
                    "ip_address": "35.161.192.168",
                    "hostname": "buildkite-ci-0c2ce33582ef1613d",
                    "user_agent": "buildkite-agent/3.22.1.x (linux; amd64)",
                    "version": "3.22.1",
                    "creator": null,
                    "created_at": "2022-03-08T17:03:51.129Z",
                    "job": null,
                    "last_job_finished_at": "2022-03-08T19:12:35.186Z",
                    "priority": 0,
                    "meta_data": [
                        "queue=v1",
                        "queue=default",
                        "queue=blue-prod",
                        "aws:instance-type=c5.4xlarge",
                        "aws:ami-id=ami-0c03484256f7dde60",
                        "aws:instance-id=i-0c2ce33582ef1613d",
                        "queues=v1,default,blue-prod",
                        "Name=buildkite-v1-0",
                        "aws:autoscaling:groupName=buildkite-v1-0",
                        "aws:ec2:fleet-id=fleet-d64b8469-f557-4a99-0cb2-a902344c4b23",
                        "aws:ec2launchtemplate:version=11",
                        "debug=false",
                        "name=buildkite-v1-0",
                        "aws:ec2launchtemplate:id=lt-0f2b1709119aaaaaa",
                        "kind=buildkite"
                    ]
                },
                "created_at": "2022-03-08T18:15:37.539Z",
                "scheduled_at": "2022-03-08T18:15:25.264Z",
                "runnable_at": "2022-03-08T18:15:37.620Z",
                "started_at": "2022-03-08T18:15:42.212Z",
                "finished_at": "2022-03-08T18:17:20.928Z",
                "retried": false,
                "retried_in_job_id": null,
                "retries_count": null,
                "retry_type": null,
                "parallel_group_index": null,
                "parallel_group_total": null,
                "matrix": null
            }
        ]
    }
]
`)

func TestJSONUnmarshal(t *testing.T) {
	t.Run("Builds", func(t *testing.T) {
		var builds []Build
		if err := json.Unmarshal(buildsResponse, &builds); err != nil {
			t.Fatal(err)
		}
		if len(builds) != 3 {
			t.Errorf("should have gotten 3 builds, got %d", len(builds))
		}
	})
}
